# permissions for end users to view finalizeroperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: finalizeroperator-viewer-role
rules:
- apiGroups:
  - finalizer.example.com
  resources:
  - finalizeroperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - finalizer.example.com
  resources:
  - finalizeroperators/status
  verbs:
  - get
