apiVersion: finalizer.example.com/v1
kind: FinalizerOperator
metadata:
  name: sample
spec:
  # Add fields here
  templateName: "trident"
  namespace: "trident"
  resources: 
    - type: "deployment"
      name: "trident-csi"
      namespace: "trident"
    - type: "deployment"
      name: "trident-operator"
      namespace: "trident"




