apiVersion: v1
kind: Pod
metadata:
  name: netapp-pod
spec:
  volumes:
  - name: test-vol
    persistentVolumeClaim:
        claimName: netapp-pvc
  containers:
  - name: app
    image: ubuntu:latest
    imagePullPolicy: Always
    command: ["sh"]
    args: ["-c", "while true; do echo date; sleep 10; done"]
    volumeMounts:
    - name: test-vol
      mountPath: "/test"