kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netapp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: sat-netapp-file-gold